name: coresvc-registry-build

on: 
    workflow_dispatch:
    push:
        branches:
         - main

jobs:
  build-coresvc-registry-amd64:
    permissions:
      contents: read
      packages: write

    uses: microsoft/azure-orbital-space-sdk-github-actions/.github/workflows/coresvc-build.yaml@0.11.0-nightly
    with:
      REGISTRY: ghcr.io
      APP_NAME: coresvc-registry
      ANNOTATION: azure-orbital-space-sdk-coresvc-registry.yaml
      WORKFLOW_AGENT: ubuntu-latest
      ARCHITECTURE: amd64
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}

  build-coresvc-registry-arm64:
    permissions:
      contents: read
      packages: write

    uses: microsoft/azure-orbital-space-sdk-github-actions/.github/workflows/coresvc-build.yaml@0.11.0-nightly
    with:
      REGISTRY: ghcr.io
      APP_NAME: coresvc-registry
      ANNOTATION: azure-orbital-space-sdk-coresvc-registry.yaml
      WORKFLOW_AGENT: spacesdk-ubuntu-2204LTS-arm64
      ARCHITECTURE: arm64
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}